### ISSUE TITLE
解析只能解析lwpolyline吗?为什么没有bul信息,能提供编译脚本吗?

### ISSUE THREAD

**Issue by FishOrBear** [shiqifeng2000/dwg-reader#1]
或者能编译个dwg-dxf的wasm库吗?

**Comment by shiqifeng2000** [comment]
目前是的，曾经尝试二维多段线，但是一直报错，就没有跟，主要是使用了libredwg进行的编译，代码比较简单，就是一个循环所有object，过滤出lwpolyline而已

On Tue, Mar 29, 2022 at 9:17 AM FishOrBear ***@***.***> wrote:
>
> Closed #1.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
Best Regards

Yours, Robin Shi
